/**
 * @author Bryce Finch
 */
package COVID19;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
//import ban.yes

/**
 *
 * @author Bryce
 */
public class mainGUI_1 extends javax.swing.JFrame {
    
    //ban dataToBan = new ban();
    
    public String selectedStatistic;
    public String selectedCountry;
    public String selectedProvence;
    public int startDateMonth;
    public int startDateDay;
    public int startDateYear;
    public int endDateMonth;
    public int endDateDay;
    public int endDateYear;
    

    /**
     * Creates new form mainGUI
     */
    public mainGUI_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        startDateMonthText = new javax.swing.JTextField();
        endDateMonthText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        confirmedRadio = new javax.swing.JRadioButton();
        recoveredRadio = new javax.swing.JRadioButton();
        deathRadio = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();
        startDateDayText = new javax.swing.JTextField();
        startDateYearText = new javax.swing.JTextField();
        endDateDaytext = new javax.swing.JTextField();
        endDateYearText = new javax.swing.JTextField();
        countryText = new javax.swing.JTextField();
        provenceText = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("COVID-19 Tracker");

        startDateMonthText.setText("MM");
        startDateMonthText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateMonthTextActionPerformed(evt);
            }
        });

        endDateMonthText.setText("MM");
        endDateMonthText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endDateMonthTextActionPerformed(evt);
            }
        });

        jLabel2.setText("Country:");

        jLabel3.setText("Provence:");

        jLabel4.setText("Start Date (MM/DD/YYYY):");

        jLabel5.setText("End Date (MM/DD/YYYY):");

        jLabel6.setText("Statistics:");

        confirmedRadio.setText("Confirmed Cases");
        confirmedRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmedRadioActionPerformed(evt);
            }
        });

        recoveredRadio.setText("Cases Recovered");
        recoveredRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recoveredRadioActionPerformed(evt);
            }
        });

        deathRadio.setText("Total Deaths");
        deathRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deathRadioActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(displayTable);

        startDateDayText.setText("DD");
        startDateDayText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateDayTextActionPerformed(evt);
            }
        });

        startDateYearText.setText("YYYY");
        startDateYearText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateYearTextActionPerformed(evt);
            }
        });

        endDateDaytext.setText("DD");
        endDateDaytext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endDateDaytextActionPerformed(evt);
            }
        });

        endDateYearText.setText("YYYY");
        endDateYearText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endDateYearTextActionPerformed(evt);
            }
        });

        countryText.setText("Country");

        provenceText.setText("Provence");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(countryText)
                                .addComponent(provenceText, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(startDateYearText))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(startDateMonthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(startDateDayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(endDateMonthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(endDateDaytext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(endDateYearText))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deathRadio)
                            .addComponent(recoveredRadio)
                            .addComponent(confirmedRadio)
                            .addComponent(jLabel6)
                            .addComponent(submitButton))
                        .addGap(26, 26, 26)))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 79, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(provenceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmedRadio)
                                .addGap(34, 34, 34))
                            .addComponent(recoveredRadio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deathRadio)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startDateMonthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateDayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(submitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endDateMonthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateDaytext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmedRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmedRadioActionPerformed
        selectedStatistic = "confirmed";
    }//GEN-LAST:event_confirmedRadioActionPerformed

    // Set All of the Values to the User Inputted Values
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        /*
        ban.setCountry(countryText.getText());
        ban.setProvence(provenceText.getText());
        ban.setSelected(selectedStatistic);
        ban.setStartMonth(startDateMonthText.getText());
        ban.setStartDay(startDateDayText.getText());
        ban.setStartYear(startDateYearText.getText());
        ban.setEndMonth(endDateMonthText.getText());
        ban.setEndDay(endDateDayText.getText());
        ban.setEndYear(endDateYearText.getText());
        
        I dont know how youre sending the values back so here is where
        the get method(s) go.
        
        populateTable(whateveDataIsFromGetMethod);
        
        
        */
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void recoveredRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recoveredRadioActionPerformed
        selectedStatistic = "recovered";
    }//GEN-LAST:event_recoveredRadioActionPerformed

    private void deathRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deathRadioActionPerformed
        selectedStatistic = "deaths";
    }//GEN-LAST:event_deathRadioActionPerformed

    private void startDateYearTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateYearTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDateYearTextActionPerformed

    private void startDateMonthTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateMonthTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDateMonthTextActionPerformed

    private void startDateDayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateDayTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDateDayTextActionPerformed

    private void endDateMonthTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endDateMonthTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endDateMonthTextActionPerformed

    private void endDateDaytextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endDateDaytextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endDateDaytextActionPerformed

    private void endDateYearTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endDateYearTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endDateYearTextActionPerformed
 
    // Populate Table
    public void populateTable() {
        /*Object[] col = {"Country", "Provence", "Selected Statistic", "Date"};
        
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        
        JTable dataTable = new JTable(tableModel);
        
        // WHERE dataList is the ArrayList of Data from the Database
        for (int i = 0; i < dataList.size(); i++) {
            String country = dataList.get(i).getCountry();
            String provence = dataList.get(i).getProvence();
            if (selectedStatistic == "confirmed"){
                int selectedStat = dataList.get(i).getConfirmed();
            }
            else if (selectedStatistic == "recovered") {
                int selectedStat = dataList.get(i).getRecovered();
            }
            else {
                int selectedStat = dataList.get(i).getDeathTotal();
            }
            String date = dataList.get(i).getDate();
            
        }
        
        Object[] data = {"Country", "Provence", "Selected Statistic", "Date"};
        
        dataTable.addRow(data);*/
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton confirmedRadio;
    private javax.swing.JTextField countryText;
    private javax.swing.JRadioButton deathRadio;
    private javax.swing.JTable displayTable;
    private javax.swing.JTextField endDateDaytext;
    private javax.swing.JTextField endDateMonthText;
    private javax.swing.JTextField endDateYearText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField provenceText;
    private javax.swing.JRadioButton recoveredRadio;
    private javax.swing.JTextField startDateDayText;
    private javax.swing.JTextField startDateMonthText;
    private javax.swing.JTextField startDateYearText;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
